name: Build dictionaries and app, then run tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-check:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Gradle build dictionaries
      run: ./gradlew buildDictionaries

    - name: Gradle build
      run: ./gradlew build

    - name: Gradle check
      run: ./gradlew check
      
    - name: Build debug version
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: assembleDebug

    - name: Sign debug .apk
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/debug
        signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
        alias: ${{ secrets.DEBUG_SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.DEBUG_KEY_STORE_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "29.0.3"
        
    - name: Upload signed debug app
      uses: actions/upload-artifact@v2
      with:
        name: Signed debug apk
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
